### ISSUE TITLE
Package won't install from PyPi - missing requirements.txt

### ISSUE THREAD

**Issue by xavriley** [bootphon/pyrpde#1]
Trying to install this recently via 

```
pip install pyrdpe
```

I received the following error:

```
Processing /Users/xavriley/Downloads/pyrpde-0.1.2
    ERROR: Command errored out with exit status 1:
     command: /Users/xavriley/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cw/qr3gl5t11xxgvwq2y99s8stw0000gn/T/pip-req-build-kro7naac/setup.py'"'"'; __file__='"'"'/private/var/folders/cw/qr3gl5t11xxgvwq2y99s8stw0000gn/T/pip-req-build-kro7naac/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/cw/qr3gl5t11xxgvwq2y99s8stw0000gn/T/pip-pip-egg-info-w2bducy_
         cwd: /private/var/folders/cw/qr3gl5t11xxgvwq2y99s8stw0000gn/T/pip-req-build-kro7naac/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/cw/qr3gl5t11xxgvwq2y99s8stw0000gn/T/pip-req-build-kro7naac/setup.py", line 13, in <module>
        with open(path.join(here, 'requirements.txt')) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/cw/qr3gl5t11xxgvwq2y99s8stw0000gn/T/pip-req-build-kro7naac/requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It looks like it's coming from this line in `setup.py` https://github.com/bootphon/pyrpde/blob/master/setup.py#L33

**Comment by xavriley** [comment]
As a temporary workaround you can download the package from https://pypi.org/project/pyrpde/, unzip it, touch requirements.txt in the root of that folder and then `pip install /path/to/extracted/folder`

**Comment by hadware** [comment]
Thanks for the report!

I think it's my fault, I might have packaged it wrong (using bdist instead of bdist_wheel). i'll submit an updated version of the package, check if that works then.

**Comment by hadware** [comment]
I submitted a new version of the package (should be `0.1.3`). It should now run fine with pip.

**Comment by xavriley** [comment]
Great - I just tried installing from pip and it worked with Python 3.7 :+1:
