### ISSUE TITLE
pip install pyrpde fails with error

### ISSUE THREAD

**Issue by xavriley** [bootphon/pyrpde#2]
Trying to install this recently via 

```
pip install pyrdpe
```

I received the following error:

```
Processing /Users/xavriley/Downloads/pyrpde-0.1.2
    ERROR: Command errored out with exit status 1:
     command: /Users/xavriley/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cw/qr3gl5t11xxgvwq2y99s8stw0000gn/T/pip-req-build-kro7naac/setup.py'"'"'; __file__='"'"'/private/var/folders/cw/qr3gl5t11xxgvwq2y99s8stw0000gn/T/pip-req-build-kro7naac/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/cw/qr3gl5t11xxgvwq2y99s8stw0000gn/T/pip-pip-egg-info-w2bducy_
         cwd: /private/var/folders/cw/qr3gl5t11xxgvwq2y99s8stw0000gn/T/pip-req-build-kro7naac/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/cw/qr3gl5t11xxgvwq2y99s8stw0000gn/T/pip-req-build-kro7naac/setup.py", line 13, in <module>
        with open(path.join(here, 'requirements.txt')) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/cw/qr3gl5t11xxgvwq2y99s8stw0000gn/T/pip-req-build-kro7naac/requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It looks like it's coming from this line in `setup.py` https://github.com/bootphon/pyrpde/blob/master/setup.py#L33

**Comment by xavriley** [comment]
sorry for the duplicate - GitHub gave me a 404 when submitting the first one
